---
title: "R Notebook"
output: html_notebook
---

# Google Places API Exploration
Pull closest X POI to my address (ranked in order of proximity)

```{r}
library(httr)
library(jsonlite)
library(dplyr)

# Establish site address
site_latitude <- 33.76977928647271
site_longitude <- -84.30220923083071

#site_latitude <- 33.81975440684414
#site_longitude <- -84.26449657910925

# Load Desirable Activities csv
desirable_activity_categories <-read.csv('your_project_directory/data/qap_scoring_tables/desirable_activity_categories.csv')

# Define the API key
my_api_key <- "your_google_api_key"
poi_type <- row$placeType

# Find nearby POI - function
# Arguments: 
# 1) Place type (Google Places) (https://developers.google.com/maps/documentation/places/web-service/supported_types)
# 2) Site latitude and longitude

get_nearby_poi <- function(poi_type, site_latitude, site_longitude, filter_text, filter_in, api_key) {

# Define the request parameters
request <- list(
  includedTypes = str_split(row$placeType, ",\\s*") ,
  locationRestriction = list(
    circle = list(
      center = list(
        latitude = site_latitude,
        longitude = site_longitude
      ),
      radius = 2414.14 #1.5 miles
    )
  ),
  rankPreference = 'DISTANCE',
  maxResultCount=20
)

# Convert the request body to JSON
json_request <- toJSON(request, auto_unbox = TRUE)

field_mask <- 'places.displayName,places.location,places.shortFormattedAddress,places.viewport'
  
# Make the POST request to the Places API
response <- POST(
  url = 'https://places.googleapis.com/v1/places:searchNearby',
  add_headers(
    'Content-Type' = 'application/json',
    'X-Goog-Api-Key' = api_key,
    'X-Goog-FieldMask' = field_mask
  ),
  body = json_request
)

# Parse the response
data <- fromJSON(content(response, as = "text"))

# Subset results from 20 (max) down to top 3 for distance search

# Reformat as data frame
if(!is.null(data$places))  {
  nearby_places <- data.frame(poi_type = poi_type,
                               name = data$places$displayName$text,
                               address = data$places$shortFormattedAddress,
                               latitude = data$places$location$latitude,
                               longitude = data$places$location$longitude)
  
  # If using a 'keep' filter (e.g. 'hospital'), narrow in on matching records
    if (filter_in == 'keep' && filter_text != "") {
      nearby_places <- nearby_places %>% 
        filter(grepl(filter_text, name, ignore.case = TRUE))
    }
  
  # If using a 'remove' filter (e.g. 'Little free library'), narrow in on matching records
    if (filter_in == 'remove' && filter_text != "") {
      nearby_places <- nearby_places %>% 
        filter(!grepl(filter_text, name, ignore.case = TRUE))
    }
  
  # Filter down to 3 closest POI
  if(nrow(nearby_places) > 0){
    nearby_places <- nearby_places[1:3,]
  } else {
    nearby_places <- data.frame()
  }
  
} else {
  # If no results within distance filter, return an empty df
  nearby_places <- data.frame()
}

return(nearby_places)
}

```

#Step 2: Take location of closest result(s) and calculate driving distances to each
Return driving distances 

```{r}

library(httr)
library(jsonlite)

# Calculate driving distances


# Function to get driving distances
get_driving_distance <- function(site_latitude, site_longitude, destinations, api_key) {
  
  # Only call API if >=1 destination is listed
  if (nrow(destinations) > 0) {
      
    # Create lat/long string for API
  site_lat_long <- paste0(site_latitude, ",", site_longitude)
  
  destination_str <- paste(apply(destinations, 1, 
                                 function(row) paste0(row["latitude"], ",", row["longitude"])), collapse = "|")
    url <- paste0(
      "https://maps.googleapis.com/maps/api/distancematrix/json?origins=",
      site_lat_long, "&destinations=", destination_str, "&key=", api_key
    )
    
    response <- GET(url)
    content <- fromJSON(content(response, "text", encoding = "UTF-8"))
    #results <- content$rows$elements
    
    results <- data.frame(destinations,
                          miles_away = round(content$rows$elements[[1]]$distance$value/1609),3)
    
    # Filter distance calcuations to closest POI (remove others)
    results <- results[1,]
  
    return(results)
  } 

}

```

Test run of POI and distance functions
```{r}


# Test run of function
#get_nearby_poi('subway_station', site_latitude, site_longitude)

if(nrow(nearby_poi) > 0) {
  nearby_poi <- get_driving_distance(site_lat_long, nearby_poi, api_key)
} else {
  # Reformat data frame so that it can be appended as empty?
  nearby_poi <- data.frame()
}
```

```{r}

poi_list <- list(
  "department_store", 
  # "department_store", # Adjust to make more specific re: Walmart/Target
  "supermarket",
  "restaurant",
  "hospital",
  "doctor", "dentist",
  "pharmacy",
  "preschool",
  "primary_school", "secondary_school",
  # "town_square", # only for rural
  "community_center",
  "park",
  "park",
  "library",
  "fire_station", "police",
  "bank",
  "church", "hindu_temple", "mosque", "synagogue",
  "post_office"
)

desirable_activity_pois <- data.frame()

for (poi in poi_list) {
  # Pull closest POI locations (3 closest)
  nearby_poi_result <- get_nearby_poi(poi, site_latitude, site_longitude)
  
  # Only run if there's a result within 1.5 miles (>0 rows in nearby_poi)
  if(nrow(nearby_poi_result) > 0) {
    
  # Add driving distance column to df  
  nearby_poi_result <- get_driving_distance(site_latitude, site_longitude, nearby_poi_result, api_key)
  
  # Append poi row to desirable_activity df
  desirable_activity_pois <- rbind(desirable_activity_pois, nearby_poi_result)
  } 
  
}


```


